me:
	@(runner=`whoami`;\
	if test $$runner != "root" ; \
	then \
		echo "What?"; \
	else \
		echo "Okay" ; \
		echo "                    _.---._			" ; \
		echo "                _.-~       ~-._			" ; \
		echo "            _.-~               ~-._		" ; \
		echo "        _.-~                       ~---._		" ; \
		echo "    _.-~                                 ~\ 	" ; \
		echo " .-~                                    _.; 	" ; \
		echo " :-._                               _.-~ ./ 	" ; \
		echo " \-._~-._                   _..__.-~ _.-~ 	" ; \
		echo "  /  ~-._~-._              / .__..--~----._ 	" ; \
		echo " \_____(_;-._\.        _.-~_/       ~).. . \ 	" ; \
		echo "    /(_____  \\--...--~_.-~______..-+_______) 	" ; \
		echo "  .(_________/\--...--~/    _/nad        /\ 	" ; \
		echo " /-._     \_     (___./_..-~__.....__..-~./ 	" ; \
		echo " \-._~-._   ~\--------~  .-~_..__.-~ _.-~		" ; \
		echo "     ~-._~-._ ~---------'  / .__..--~		" ; \
		echo "         ~-._\.        _.-~_/			" ; \
		echo "             \\--...--~_.-~			" ; \
		echo "              \--...--~ 				" ; \
	fi)

a:
	@(runner=`whoami`;\
	if test $$runner != "root" ; \
	then \
	    echo "Make it yourself";\
	fi)
sandwich:
	    @(echo "")
