
me:
	@(runner=`whoami`;\
	if test $$runner != "root" ; \
	then \
		echo "What?"; \
	else \
		echo "Okay" ; \
	fi)

a:
	@(runner=`whoami`;\
	if test $$runner != "root" ; \
	then \
	    echo "Make it yourself";\
	fi)
sandwich:
	    @(echo "")
