#!/bin/bash
dinero () {
	# dinro nom_experience  arguments_dinero
	expe=$1
	t=$2
	shift 2 
	'./d4-7/dineroIV' -informat d  $*> log/tmp
	nf=`awk '/^[[:space:]]+Demand Fetches/ { print $3}' < log/tmp` 
	nmiss=`awk '/Demand miss rate/ { printf("%s ",$4)}' < log/tmp` 
	nread=`awk '/Total Bytes/{ printf("%s ", $5)}' < log/tmp` 
	echo "res : " $nf $nmiss $nread
	nf_num=( $nf )
	miss_num=( $nmiss )

	if [[ $* =~ "l2" ]];
	then
		time=$( echo 'scale=10; ( '"${nf_num[0]}"' - '"${nf_num[1]}"' ) + '"${nf_num[1]}"' * ( 10 * ( 1 - '"${miss_num[1]}"' ) + 250 * '"${miss_num[1]}"' ) ' | bc)
	else
		time=$( echo 'scale=10;  '"${nf_num[0]}"' * ( ( 1 - '"${miss_num[0]}"' ) + 250 * '"${miss_num[0]}"' )' | bc)
	fi

	echo "$t $nmiss $nread $time" >> ${expe}
}

rot () {
	# rot nom_experience t alpha arguments_dinero
	echo $*
	expe=$1
	t=$2
	alpha=$3
	shift 3
	din_arg=$*
	./rotation 512 512 $t $t ${alpha} > log/r${t}_idx
	if [[ "${expe}"  =~ "OBL" ]];
	then
		lc=`echo $din_arg | sed -r -e 's/.*bsize ([0-9]+).*/\1/g'` 
		./xy_to_adr_OBL 512 512  $lc < log/r${t}_idx > log/r${t}_adr
	else
		./xy_to_adr 512 512 < log/r${t}_idx > log/r${t}_adr
	fi
	dinero ${expe} ${t} ${din_arg}  < log/r${t}_adr 
}

boucle () {
	# boucle nom_experience increment_t t_maximum alpha arguments_dinero
	expe=$1
	rm ${expe}
	t_inc=$2
	t=$t_inc
	t_max=$3
	alpha=$4
	shift 4
	dinero_arg=$*
	rot ${expe} 1   ${alpha} $dinero_arg
	rot ${expe} 2  ${alpha} $dinero_arg
	rot ${expe} 4  ${alpha} $dinero_arg

	while [ $t -le $t_max ];
	do
		rot ${expe} $t $alpha  $dinero_arg
		t=`expr $t + $t_inc`
	done 

	output="set terminal postscript; set output \"${expe}.ps\""
if [[ $dinero_arg =~ "l2" ]];
then
	gnuplot -persist << _fin 
${output}
set title "${dinero_arg}"
set multiplot layout 3,1
set yrange [0:1]
set xlabel "t"
set ylabel "Miss rate"
plot "${expe}" using (\$1):(\$2) title "Miss rate l1" w l,  "${expe}" using (\$1):(\$3) title "Miss rate l2" w l
set yrange [0:*]
set xlabel "t"
set ylabel "Bytes from memory"
plot  "${expe}" using (\$1):(\$4) title "Bytes from memory l1" w l,  "${expe}" using (\$1):(\$5) title "Bytes from memory l2" w l
set yrange [0:*]
set xlabel "t"
set ylabel "Cycles"
plot  "${expe}" using (\$1):(\$6) title "Cycles" w l
unset multiplot
_fin
else
	gnuplot -persist << _fin 
${output}
set title "${dinero_arg}"
set multiplot layout 3,1
set yrange [0:1]
set xlabel "t"
set ylabel "Miss rate"
plot "${expe}" using (\$1):(\$2) title "Miss rate" w l
set yrange [0:*]
set xlabel "t"
set ylabel "Bytes from memory"
plot  "${expe}" using (\$1):(\$3) title "Bytes from memory" w l
set yrange [0:*]
set xlabel "t"
set ylabel "Cycles"
plot  "${expe}" using (\$1):(\$4) title "Cycles" w l
unset multiplot
_fin

fi
ps2pdf ${expe}.ps ${expe}.pdf
}
